# Generated by Django 4.1.3 on 2022-11-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_alter_attributename_zobraziť'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributename',
            old_name='zobraziť',
            new_name='zobrazit',
        ),
    ]
